"""Stage 8: the models.

Five of them, because there are five questions and conflating them is the most common
analytical error in this domain.

    baseline.base_rate    the historical approval rate. The benchmark everything must beat.
    baseline.boosted      XGBoost. The honest floor, and the thing the Bayesian model has to beat.
    hierarchical          partial pooling in NumPyro. Degrades gracefully on thin jurisdictions.
    survival              time to decision, with right censoring and competing risks.
    rulechange            will the rules change before a decision is reached.

The architectural rule that matters most, from section 6.8: no language model produces the
number. Language models extract facts and write sentences. The probability comes from a
statistical model that can be back tested and calibrated. A number generated by a language
model cannot be calibrated, cannot be back tested, cannot be audited, and therefore cannot be
sold to a credit committee or accepted by an insurer.
"""

from __future__ import annotations
