"""The Permission Graph.

Creates every table in section 6.6 of the specification plus the operational tables the
pipeline needs: the corpus and its page level provenance, the entity resolution audit
trail, point in time feature snapshots, model runs, the append only prediction ledger, and
the monitoring surface.

The extensions this schema depends on (postgis, pg_trgm, vector, btree_gist) are created by
the bootstrap script or the compose service, because CREATE EXTENSION needs superuser and
migrations run as the application role. This migration asserts they are present and refuses
to run if they are not, so a half provisioned database fails here rather than three stages
downstream.

Revision ID: 0001_permission_graph
Revises:
Created: 2026-08-27
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_permission_graph"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

REQUIRED_EXTENSIONS = ("postgis", "pg_trgm", "vector", "btree_gist")


def _assert_extensions() -> None:
    bind = op.get_bind()
    installed = {
        row[0] for row in bind.execute(sa.text("SELECT extname FROM pg_extension")).all()
    }
    missing = [name for name in REQUIRED_EXTENSIONS if name not in installed]
    if missing:
        raise RuntimeError(
            "missing required PostgreSQL extensions: "
            + ", ".join(missing)
            + ". Run infra/scripts/bootstrap-postgres.ps1 (Windows) or "
            "docker compose -f infra/docker-compose.yml up -d db."
        )


def upgrade() -> None:
    _assert_extensions()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_cluster",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.Text(), nullable=False, comment="applicant, owner, objection_group"),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column(
            "beneficial_owner_name",
            sa.Text(),
            nullable=True,
            comment="Where the record discloses the principal behind a single purpose entity",
        ),
        sa.Column("opaque", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('applicant','owner','objection_group')",
            name=op.f("ck_entity_cluster_ck_entity_cluster_kind_vocabulary"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_cluster")),
    )
    op.create_index(
        "ix_entity_cluster_canonical_name_trgm",
        "entity_cluster",
        ["canonical_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"canonical_name": "gin_trgm_ops"},
    )
    op.create_table(
        "jurisdiction",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "slug",
            sa.Text(),
            nullable=False,
            comment="Stable human readable key, e.g. us-va-loudoun",
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), server_default=sa.text("'US'"), nullable=False),
        sa.Column("region", sa.Text(), nullable=True, comment="State or province code"),
        sa.Column(
            "admin_codes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="FIPS, GEOID, ONS or equivalent official identifiers",
        ),
        sa.Column(
            "legal_framework",
            sa.Text(),
            nullable=True,
            comment="Dillon's Rule versus home rule. Determines whether the state can pre-empt.",
        ),
        sa.Column(
            "boundary",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
            comment="Official boundary. Null only while the registry entry is being built.",
        ),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("land_area_sq_km", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("civic_platform", sa.Text(), nullable=True),
        sa.Column(
            "discretion_index",
            sa.Numeric(precision=4, scale=3),
            nullable=True,
            comment="0 fully by right, 1 fully discretionary. The channel politics arrives through.",
        ),
        sa.Column(
            "data_depth",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Usable historical decisions held. Drives the abstention rule in section 8.4.",
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "civic_platform IS NULL OR civic_platform IN ('legistar', 'civicplus', 'accela', 'opengov', 'municode', 'granicus', 'unknown')",
            name=op.f("ck_jurisdiction_platform_vocabulary"),
        ),
        sa.CheckConstraint(
            "kind IN ('county', 'municipality', 'township', 'special_district', 'state_agency', 'federal_agency', 'utility', 'grid_operator')",
            name=op.f("ck_jurisdiction_kind_vocabulary"),
        ),
        sa.CheckConstraint(
            "legal_framework IS NULL OR legal_framework IN ('dillons_rule', 'home_rule', 'mixed')",
            name=op.f("ck_jurisdiction_framework_vocabulary"),
        ),
        sa.CheckConstraint(
            "data_depth >= 0", name=op.f("ck_jurisdiction_ck_jurisdiction_data_depth_nonneg")
        ),
        sa.CheckConstraint(
            "discretion_index IS NULL OR (discretion_index >= 0 AND discretion_index <= 1)",
            name=op.f("ck_jurisdiction_ck_jurisdiction_discretion_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jurisdiction")),
        sa.UniqueConstraint("country", "kind", "name", name="uq_jurisdiction_country_kind_name"),
        sa.UniqueConstraint("slug", name="uq_jurisdiction_slug"),
    )
    op.create_index(
        "ix_jurisdiction_boundary",
        "jurisdiction",
        ["boundary"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "ix_jurisdiction_name_trgm",
        "jurisdiction",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index("ix_jurisdiction_region_kind", "jurisdiction", ["region", "kind"], unique=False)
    op.create_table(
        "merge_audit",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("entity_kind", sa.Text(), nullable=False),
        sa.Column("absorbed_id", sa.BigInteger(), nullable=False),
        sa.Column("survivor_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "method",
            sa.Text(),
            nullable=False,
            comment="exact, trigram, embedding, llm_adjudication, manual",
        ),
        sa.Column("score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "merged_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversed_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "method IN ('exact','trigram','embedding','llm_adjudication','manual')",
            name=op.f("ck_merge_audit_ck_merge_audit_method_vocabulary"),
        ),
        sa.CheckConstraint(
            "absorbed_id <> survivor_id", name=op.f("ck_merge_audit_ck_merge_audit_not_self")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merge_audit")),
    )
    op.create_table(
        "model_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "version", sa.Text(), nullable=False, comment="Semantic version of the model definition"
        ),
        sa.Column("feature_set_version", sa.Text(), nullable=False),
        sa.Column(
            "dataset_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 over the sorted training rows. Two runs with the same hash saw the same data, which is what makes the public accuracy record reproducible.",
        ),
        sa.Column("train_cutoff", sa.Date(), nullable=False),
        sa.Column("n_train", sa.Integer(), nullable=False),
        sa.Column("n_test", sa.Integer(), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "calibrator",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Fitted isotonic or Platt parameters",
        ),
        sa.Column("artifact_path", sa.Text(), nullable=True),
        sa.Column(
            "trained_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "promoted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When it began serving",
        ),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('base_rate', 'gradient_boosted', 'hierarchical', 'survival', 'rule_change')",
            name=op.f("ck_model_run_kind_vocabulary"),
        ),
        sa.CheckConstraint(
            "n_train >= 0 AND n_test >= 0", name=op.f("ck_model_run_ck_model_run_counts_nonneg")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_run")),
        sa.UniqueConstraint(
            "kind", "version", "dataset_hash", name="uq_model_run_kind_version_dataset_hash"
        ),
    )
    op.create_index(
        "ix_model_run_serving",
        "model_run",
        ["kind", "promoted_at"],
        unique=False,
        postgresql_where=sa.text("retired_at IS NULL"),
    )
    op.create_table(
        "dead_letter",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "stage",
            sa.Text(),
            nullable=False,
            comment="ingest, parse, transcribe, extract, resolve",
        ),
        sa.Column(
            "subject",
            sa.Text(),
            nullable=False,
            comment="A URL, a document id, or an application id",
        ),
        sa.Column("jurisdiction_id", sa.BigInteger(), nullable=True),
        sa.Column("error_type", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "stage IN ('ingest','parse','transcribe','extract','resolve','feature','score')",
            name=op.f("ck_dead_letter_ck_dead_letter_stage_vocabulary"),
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdiction.id"],
            name=op.f("fk_dead_letter_jurisdiction_id_jurisdiction"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dead_letter")),
        sa.UniqueConstraint("stage", "subject", name="uq_dead_letter_stage_subject"),
    )
    op.create_index(
        "ix_dead_letter_open",
        "dead_letter",
        ["stage", "last_seen_at"],
        unique=False,
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.create_table(
        "decision_body",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("jurisdiction_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=True),
        sa.Column("quorum", sa.Integer(), nullable=True),
        sa.Column(
            "vote_threshold",
            sa.Text(),
            nullable=True,
            comment="simple_majority, supermajority_two_thirds, supermajority_three_quarters, unanimity",
        ),
        sa.Column(
            "recommendation_is_binding",
            sa.Boolean(),
            nullable=True,
            comment="Whether this body's recommendation binds the body above it. Appendix 19.2 group A.",
        ),
        sa.Column("meeting_cadence", sa.Text(), nullable=True),
        sa.Column(
            "statutory_decision_days",
            sa.Integer(),
            nullable=True,
            comment="Statutory deadline where one exists. Enforcement in practice is a separate feature.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('planning_commission', 'board_of_supervisors', 'county_commission', 'city_council', 'zoning_board', 'board_of_adjustment', 'plan_commission', 'staff', 'other')",
            name=op.f("ck_decision_body_kind_vocabulary"),
        ),
        sa.CheckConstraint(
            "quorum IS NULL OR seats IS NULL OR quorum <= seats",
            name=op.f("ck_decision_body_ck_decision_body_quorum_lte_seats"),
        ),
        sa.CheckConstraint(
            "seats IS NULL OR seats > 0",
            name=op.f("ck_decision_body_ck_decision_body_seats_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdiction.id"],
            name=op.f("fk_decision_body_jurisdiction_id_jurisdiction"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_body")),
        sa.UniqueConstraint(
            "jurisdiction_id", "name", name="uq_decision_body_jurisdiction_id_name"
        ),
    )
    op.create_table(
        "parcel",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("jurisdiction_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "external_id", sa.Text(), nullable=True, comment="Assessor parcel number as published"
        ),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("acres", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("current_zoning", sa.Text(), nullable=True),
        sa.Column(
            "overlays", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False
        ),
        sa.Column("owner_raw", sa.Text(), nullable=True),
        sa.Column("owner_cluster_id", sa.BigInteger(), nullable=True),
        sa.Column("prior_industrial_use", sa.Boolean(), nullable=True),
        sa.Column(
            "valid_from",
            sa.Date(),
            nullable=False,
            comment="Parcels split, merge and get renumbered. Bi-temporal so a 2024 score sees the 2024 geometry.",
        ),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acres IS NULL OR acres > 0", name=op.f("ck_parcel_ck_parcel_acres_positive")
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_parcel_ck_parcel_validity_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdiction.id"],
            name=op.f("fk_parcel_jurisdiction_id_jurisdiction"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_cluster_id"],
            ["entity_cluster.id"],
            name=op.f("fk_parcel_owner_cluster_id_entity_cluster"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parcel")),
    )
    op.create_index("ix_parcel_geom", "parcel", ["geom"], unique=False, postgresql_using="gist")
    op.create_index(
        "ix_parcel_jurisdiction_id_external_id",
        "parcel",
        ["jurisdiction_id", "external_id"],
        unique=False,
    )
    op.create_index("ix_parcel_owner_cluster_id", "parcel", ["owner_cluster_id"], unique=False)
    op.create_table(
        "source",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("jurisdiction_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "kind", sa.Text(), nullable=False, comment="Which DocumentKind this source yields"
        ),
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "platform_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Adapter specific handles: Legistar client name, CivicPlus module id, and so on",
        ),
        sa.Column(
            "refresh_hours",
            sa.Integer(),
            server_default=sa.text("24"),
            nullable=False,
            comment="Freshness SLA from section 6.12, in hours",
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "robots_allowed", sa.Boolean(), nullable=True, comment="Null means not yet checked"
        ),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "consecutive_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('agenda', 'minutes', 'staff_report', 'ordinance', 'resolution', 'comprehensive_plan', 'application_packet', 'transcript', 'docket', 'legal_notice', 'news_article', 'parcel_record', 'election_record', 'other')",
            name=op.f("ck_source_kind_vocabulary"),
        ),
        sa.CheckConstraint(
            "platform IN ('legistar', 'civicplus', 'accela', 'opengov', 'municode', 'granicus', 'unknown')",
            name=op.f("ck_source_platform_vocabulary"),
        ),
        sa.CheckConstraint("refresh_hours > 0", name=op.f("ck_source_ck_source_refresh_positive")),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdiction.id"],
            name=op.f("fk_source_jurisdiction_id_jurisdiction"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
        sa.UniqueConstraint(
            "jurisdiction_id", "kind", "url", name="uq_source_jurisdiction_id_kind_url"
        ),
    )
    op.create_index(
        "ix_source_enabled_last_success_at", "source", ["enabled", "last_success_at"], unique=False
    )
    op.create_table(
        "application",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("jurisdiction_id", sa.BigInteger(), nullable=False),
        sa.Column("body_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "external_id",
            sa.Text(),
            nullable=True,
            comment="Case number as the jurisdiction publishes it",
        ),
        sa.Column("applicant_raw", sa.Text(), nullable=True),
        sa.Column("applicant_cluster_id", sa.BigInteger(), nullable=True),
        sa.Column("parcel_id", sa.BigInteger(), nullable=True),
        sa.Column("use_class", sa.Text(), nullable=False),
        sa.Column("relief_sought", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("by_right", sa.Boolean(), nullable=True),
        sa.Column("capacity_mw", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("acres", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("filed_on", sa.Date(), nullable=True),
        sa.Column("decided_on", sa.Date(), nullable=True),
        sa.Column("outcome", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("vote_for", sa.Integer(), nullable=True),
        sa.Column("vote_against", sa.Integer(), nullable=True),
        sa.Column("vote_abstain", sa.Integer(), nullable=True),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "staff_recommendation",
            sa.Text(),
            nullable=True,
            comment="approve, approve_with_conditions, deny, none. Whether the body overruled its own staff is one of the stronger features.",
        ),
        sa.Column(
            "months_to_decision",
            sa.Numeric(precision=8, scale=3),
            sa.Computed(
                "CASE WHEN decided_on IS NOT NULL AND filed_on IS NOT NULL THEN (decided_on - filed_on) / 30.44 END",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "censored",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Still pending. Right censored, not missing. Section 6.8 model 2.",
        ),
        sa.Column(
            "label_source",
            sa.Text(),
            server_default=sa.text("'extracted'"),
            nullable=False,
            comment="hand_labelled or extracted. Hand labelled rows are the training ground truth.",
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(censored = true) = (outcome IN ('pending','continued','tabled','unknown'))",
            name=op.f("ck_application_ck_application_censored_matches_outcome"),
        ),
        sa.CheckConstraint(
            "label_source IN ('hand_labelled','extracted')",
            name=op.f("ck_application_ck_application_label_source_vocabulary"),
        ),
        sa.CheckConstraint(
            "outcome IN ('approved', 'approved_with_conditions', 'denied', 'withdrawn', 'continued', 'tabled', 'pending', 'unknown')",
            name=op.f("ck_application_outcome_vocabulary"),
        ),
        sa.CheckConstraint(
            "outcome NOT IN ('approved','approved_with_conditions','denied') OR decided_on IS NOT NULL",
            name=op.f("ck_application_ck_application_decided_has_date"),
        ),
        sa.CheckConstraint(
            "relief_sought <@ ARRAY['rezoning', 'special_use_permit', 'conditional_use_permit', 'variance', 'site_plan_approval', 'comprehensive_plan_amendment', 'text_amendment', 'annexation', 'development_agreement', 'tax_abatement', 'subdivision_plat', 'other']::text[]",
            name=op.f("ck_application_relief_vocabulary"),
        ),
        sa.CheckConstraint(
            "staff_recommendation IS NULL OR staff_recommendation IN ('approve','approve_with_conditions','deny','none')",
            name=op.f("ck_application_ck_application_staff_recommendation_vocabulary"),
        ),
        sa.CheckConstraint(
            "use_class IN ('data_center_hyperscale', 'data_center_colocation', 'data_center_edge', 'solar_utility', 'wind_onshore', 'battery_storage', 'substation_transmission', 'industrial_general', 'warehouse_logistics', 'residential_multifamily', 'other')",
            name=op.f("ck_application_use_class_vocabulary"),
        ),
        sa.CheckConstraint(
            "cardinality(relief_sought) >= 1",
            name=op.f("ck_application_ck_application_relief_not_empty"),
        ),
        sa.CheckConstraint(
            "decided_on IS NULL OR filed_on IS NULL OR decided_on >= filed_on",
            name=op.f("ck_application_ck_application_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["applicant_cluster_id"],
            ["entity_cluster.id"],
            name=op.f("fk_application_applicant_cluster_id_entity_cluster"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["body_id"],
            ["decision_body.id"],
            name=op.f("fk_application_body_id_decision_body"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdiction.id"],
            name=op.f("fk_application_jurisdiction_id_jurisdiction"),
        ),
        sa.ForeignKeyConstraint(
            ["parcel_id"],
            ["parcel.id"],
            name=op.f("fk_application_parcel_id_parcel"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application")),
        sa.UniqueConstraint(
            "jurisdiction_id", "external_id", name="uq_application_jurisdiction_id_external_id"
        ),
    )
    op.create_index(
        "ix_application_applicant_cluster_id", "application", ["applicant_cluster_id"], unique=False
    )
    op.create_index("ix_application_filed_on", "application", ["filed_on"], unique=False)
    op.create_index(
        "ix_application_jurisdiction_id_use_class_decided_on",
        "application",
        ["jurisdiction_id", "use_class", "decided_on"],
        unique=False,
    )
    op.create_index(
        "ix_application_outcome_decided_on", "application", ["outcome", "decided_on"], unique=False
    )
    op.create_index(
        "ix_application_pending",
        "application",
        ["jurisdiction_id", "filed_on"],
        unique=False,
        postgresql_where=sa.text("censored = true"),
    )
    op.create_table(
        "decision_maker",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("body_id", sa.BigInteger(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "name_variants",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
            comment="Every spelling seen in a source. Never destroyed. Section 6.5.",
        ),
        sa.Column("seat_label", sa.Text(), nullable=True),
        sa.Column("term_start", sa.Date(), nullable=True),
        sa.Column(
            "term_end", sa.Date(), nullable=True, comment="Election proximity is a live feature"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "term_end IS NULL OR term_start IS NULL OR term_end >= term_start",
            name=op.f("ck_decision_maker_ck_decision_maker_term_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["body_id"],
            ["decision_body.id"],
            name=op.f("fk_decision_maker_body_id_decision_body"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_maker")),
    )
    op.create_index("ix_decision_maker_body_id", "decision_maker", ["body_id"], unique=False)
    op.create_index(
        "ix_decision_maker_display_name_trgm",
        "decision_maker",
        ["display_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"display_name": "gin_trgm_ops"},
    )
    op.create_table(
        "document",
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
            comment="Lowercase hex SHA-256 of the raw bytes. Re-fetching unchanged content is a no-op.",
        ),
        sa.Column("jurisdiction_id", sa.BigInteger(), nullable=True),
        sa.Column("source_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("media_type", sa.Text(), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_on", sa.Date(), nullable=True),
        sa.Column(
            "storage_key",
            sa.Text(),
            nullable=False,
            comment="Key in the raw object store. Layout is sha256[0:2]/sha256[2:4]/sha256",
        ),
        sa.Column(
            "response_headers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Kept so a later dispute about what a source said on a date is answerable",
        ),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("parse_method", sa.Text(), nullable=True),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "legibility",
            sa.Numeric(precision=4, scale=3),
            nullable=True,
            comment="Mean page legibility, 0 to 1",
        ),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "id ~ '^[0-9a-f]{64}$'", name=op.f("ck_document_ck_document_id_is_sha256")
        ),
        sa.CheckConstraint(
            "kind IN ('agenda', 'minutes', 'staff_report', 'ordinance', 'resolution', 'comprehensive_plan', 'application_packet', 'transcript', 'docket', 'legal_notice', 'news_article', 'parcel_record', 'election_record', 'other')",
            name=op.f("ck_document_kind_vocabulary"),
        ),
        sa.CheckConstraint(
            "parse_method IS NULL OR parse_method IN ('pymupdf', 'pdfplumber', 'tesseract', 'vision_model', 'native_text', 'transcription')",
            name=op.f("ck_document_parse_method_vocabulary"),
        ),
        sa.CheckConstraint(
            "byte_size > 0", name=op.f("ck_document_ck_document_byte_size_positive")
        ),
        sa.CheckConstraint(
            "legibility IS NULL OR (legibility >= 0 AND legibility <= 1)",
            name=op.f("ck_document_ck_document_legibility_range"),
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdiction.id"],
            name=op.f("fk_document_jurisdiction_id_jurisdiction"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_document_source_id_source")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document")),
    )
    op.create_index(
        "ix_document_embedding_hnsw",
        "document",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    op.create_index("ix_document_fetched_at", "document", ["fetched_at"], unique=False)
    op.create_index(
        "ix_document_jurisdiction_id_kind_published_on",
        "document",
        ["jurisdiction_id", "kind", "published_on"],
        unique=False,
    )
    op.create_index("ix_document_source_url", "document", ["source_url"], unique=False)
    op.create_table(
        "election",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("body_id", sa.BigInteger(), nullable=False),
        sa.Column("election_date", sa.Date(), nullable=False),
        sa.Column("seats_contested", sa.Integer(), nullable=True),
        sa.Column("filing_deadline", sa.Date(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=True, comment="general, primary, special, runoff"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "seats_contested IS NULL OR seats_contested >= 0",
            name=op.f("ck_election_ck_election_seats_nonneg"),
        ),
        sa.ForeignKeyConstraint(
            ["body_id"],
            ["decision_body.id"],
            name=op.f("fk_election_body_id_decision_body"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_election")),
        sa.UniqueConstraint("body_id", "election_date", name="uq_election_body_id_election_date"),
    )
    op.create_index("ix_election_election_date", "election", ["election_date"], unique=False)
    op.create_table(
        "change_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("jurisdiction_id", sa.BigInteger(), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("detected_on", sa.Date(), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "materiality",
            sa.Numeric(precision=4, scale=3),
            nullable=False,
            comment="0 to 1. Alerts below the send threshold are recorded but not delivered, because an alert system that cries wolf gets muted in a week.",
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "trigger IN ('rule_changed', 'moratorium_on_agenda', 'moratorium_enacted', 'comparable_denied_nearby', 'board_composition_changed', 'litigation_filed', 'use_class_on_agenda', 'score_moved', 'source_stale')",
            name=op.f("ck_change_event_trigger_vocabulary"),
        ),
        sa.CheckConstraint(
            "materiality >= 0 AND materiality <= 1",
            name=op.f("ck_change_event_ck_change_event_materiality_range"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.id"], name=op.f("fk_change_event_document_id_document")
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdiction.id"],
            name=op.f("fk_change_event_jurisdiction_id_jurisdiction"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_event")),
    )
    op.create_index(
        "ix_change_event_jurisdiction_id_detected_on",
        "change_event",
        ["jurisdiction_id", "detected_on"],
        unique=False,
    )
    op.create_table(
        "document_chunk",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "heading",
            sa.Text(),
            nullable=True,
            comment="The structural boundary this chunk was split on: section, agenda item, motion block",
        ),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_estimate", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.CheckConstraint(
            "char_end > char_start",
            name=op.f("ck_document_chunk_ck_document_chunk_offsets_ordered"),
        ),
        sa.CheckConstraint(
            "page_end >= page_start", name=op.f("ck_document_chunk_ck_document_chunk_pages_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_document_chunk_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunk")),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_document_chunk_document_id_ordinal"),
    )
    op.create_index(
        "ix_document_chunk_embedding_hnsw",
        "document_chunk",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    op.create_index(
        "ix_document_chunk_text_fts",
        "document_chunk",
        [sa.literal_column("to_tsvector('english', text)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "document_page",
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "char_start",
            sa.Integer(),
            nullable=False,
            comment="Offset of this page within the concatenated document text",
        ),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("parse_method", sa.Text(), nullable=False),
        sa.Column("legibility", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("escalated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "parse_method IN ('pymupdf', 'pdfplumber', 'tesseract', 'vision_model', 'native_text', 'transcription')",
            name=op.f("ck_document_page_parse_method_vocabulary"),
        ),
        sa.CheckConstraint(
            "char_end >= char_start", name=op.f("ck_document_page_ck_document_page_offsets_ordered")
        ),
        sa.CheckConstraint(
            "legibility >= 0 AND legibility <= 1",
            name=op.f("ck_document_page_ck_document_page_legibility_range"),
        ),
        sa.CheckConstraint(
            "page >= 1", name=op.f("ck_document_page_ck_document_page_page_positive")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_document_page_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("document_id", "page", name=op.f("pk_document_page")),
    )
    op.create_table(
        "entity_alias",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cluster_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "raw_string",
            sa.Text(),
            nullable=False,
            comment="Exactly as it appeared. Never normalised in place.",
        ),
        sa.Column("normalised", sa.Text(), nullable=False),
        sa.Column("first_seen_document_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["entity_cluster.id"],
            name=op.f("fk_entity_alias_cluster_id_entity_cluster"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_document_id"],
            ["document.id"],
            name=op.f("fk_entity_alias_first_seen_document_id_document"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_alias")),
        sa.UniqueConstraint(
            "cluster_id", "raw_string", name="uq_entity_alias_cluster_id_raw_string"
        ),
    )
    op.create_index(
        "ix_entity_alias_normalised_trgm",
        "entity_alias",
        ["normalised"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"normalised": "gin_trgm_ops"},
    )
    op.create_table(
        "extraction_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column(
            "cache_key",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 of document id, prompt version, schema version and model. Reprocessing unchanged input costs nothing.",
        ),
        sa.Column("schema_name", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("pass_number", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "status",
            sa.Text(),
            nullable=False,
            comment="ok, schema_violation, quote_unverified, refused, provider_error, disagreement",
        ),
        sa.Column("facts_extracted", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("facts_discarded", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ok','schema_violation','quote_unverified','refused','provider_error','disagreement')",
            name=op.f("ck_extraction_run_ck_extraction_run_status_vocabulary"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_extraction_run_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_run")),
        sa.UniqueConstraint(
            "cache_key", "pass_number", name="uq_extraction_run_cache_key_pass_number"
        ),
    )
    op.create_index(
        "ix_extraction_run_document_id", "extraction_run", ["document_id"], unique=False
    )
    op.create_index(
        "ix_extraction_run_status_created_at",
        "extraction_run",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "fact_evidence",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("subject_table", sa.Text(), nullable=False),
        sa.Column("subject_id", sa.BigInteger(), nullable=False),
        sa.Column("field", sa.Text(), nullable=True),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=True),
        sa.Column("char_end", sa.Integer(), nullable=True),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("extractor_version", sa.Text(), nullable=False),
        sa.Column(
            "verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="The quote was found verbatim in the stored source text. Unverified rows are deleted by the extraction layer, so a false here means an audit is in progress.",
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "subject_table IN ('application','instrument','objection','decision_maker','vote','jurisdiction','decision_body','election','parcel')",
            name=op.f("ck_fact_evidence_ck_fact_evidence_subject_table_vocabulary"),
        ),
        sa.CheckConstraint(
            "length(quote) BETWEEN 1 AND 500",
            name=op.f("ck_fact_evidence_ck_fact_evidence_quote_length"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.id"], name=op.f("fk_fact_evidence_document_id_document")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_evidence")),
    )
    op.create_index("ix_fact_evidence_document_id", "fact_evidence", ["document_id"], unique=False)
    op.create_index(
        "ix_fact_evidence_subject_table_subject_id",
        "fact_evidence",
        ["subject_table", "subject_id"],
        unique=False,
    )
    op.create_index(
        "ix_fact_evidence_unverified",
        "fact_evidence",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("verified = false"),
    )
    op.create_table(
        "feature_snapshot",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False, comment="Almost always the filing date"),
        sa.Column("feature_set_version", sa.Text(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "missing",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
            comment="Named features that could not be computed. Never silently zero filled.",
        ),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
            name=op.f("fk_feature_snapshot_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_snapshot")),
        sa.UniqueConstraint(
            "application_id",
            "as_of",
            "feature_set_version",
            name="uq_feature_snapshot_application_id_as_of_feature_set_version",
        ),
    )
    op.create_index("ix_feature_snapshot_as_of", "feature_snapshot", ["as_of"], unique=False)
    op.create_table(
        "fetch_attempt",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("document_id", sa.String(length=64), nullable=True),
        sa.Column(
            "outcome",
            sa.Text(),
            nullable=False,
            comment="stored, unchanged, robots_disallowed, http_error, timeout, parse_refused",
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "outcome IN ('stored','unchanged','robots_disallowed','http_error','timeout','parse_refused')",
            name=op.f("ck_fetch_attempt_ck_fetch_attempt_outcome_vocabulary"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.id"], name=op.f("fk_fetch_attempt_document_id_document")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_fetch_attempt_source_id_source"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fetch_attempt")),
    )
    op.create_index(
        "ix_fetch_attempt_source_id_attempted_at",
        "fetch_attempt",
        ["source_id", "attempted_at"],
        unique=False,
    )
    op.create_table(
        "instrument",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("jurisdiction_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("citation", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("adopted_on", sa.Date(), nullable=True),
        sa.Column("effective_on", sa.Date(), nullable=True),
        sa.Column(
            "expires_on",
            sa.Date(),
            nullable=True,
            comment="Moratoria expire. That date is a feature.",
        ),
        sa.Column(
            "supersedes_id",
            sa.BigInteger(),
            nullable=True,
            comment="Lets the system know the rules changed last month, which section 6.6 names as the most common cause of a wrong forecast",
        ),
        sa.Column(
            "applies_to_use_classes",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
            comment="Empty means it applies to everything",
        ),
        sa.Column(
            "restrictions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Structured limits: setback_ft, height_ft, noise_dba, water_gpd_cap, min_acres, mw_cap. Converts legal text into continuous numbers.",
        ),
        sa.Column("full_text_document_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "applies_to_use_classes <@ ARRAY['data_center_hyperscale', 'data_center_colocation', 'data_center_edge', 'solar_utility', 'wind_onshore', 'battery_storage', 'substation_transmission', 'industrial_general', 'warehouse_logistics', 'residential_multifamily', 'other']::text[]",
            name=op.f("ck_instrument_use_classes_vocabulary"),
        ),
        sa.CheckConstraint(
            "kind IN ('zoning_ordinance', 'overlay_district', 'moratorium', 'comprehensive_plan', 'text_amendment', 'resolution', 'state_statute', 'interim_control')",
            name=op.f("ck_instrument_kind_vocabulary"),
        ),
        sa.CheckConstraint(
            "expires_on IS NULL OR effective_on IS NULL OR expires_on >= effective_on",
            name=op.f("ck_instrument_ck_instrument_dates_ordered"),
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_instrument_ck_instrument_not_self_superseding"),
        ),
        sa.ForeignKeyConstraint(
            ["full_text_document_id"],
            ["document.id"],
            name=op.f("fk_instrument_full_text_document_id_document"),
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdiction.id"],
            name=op.f("fk_instrument_jurisdiction_id_jurisdiction"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["instrument.id"],
            name=op.f("fk_instrument_supersedes_id_instrument"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instrument")),
    )
    op.create_index(
        "ix_instrument_jurisdiction_id_kind_effective_on",
        "instrument",
        ["jurisdiction_id", "kind", "effective_on"],
        unique=False,
    )
    op.create_index(
        "ix_instrument_live_moratorium",
        "instrument",
        ["jurisdiction_id", "expires_on"],
        unique=False,
        postgresql_where=sa.text("kind = 'moratorium'"),
    )
    op.create_table(
        "jurisdiction_chain",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=False),
        sa.Column("jurisdiction_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "role IN ('primary_decider', 'recommending', 'clearance', 'load_approval', 'water_approval', 'appellate')",
            name=op.f("ck_jurisdiction_chain_role_vocabulary"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
            name=op.f("fk_jurisdiction_chain_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdiction.id"],
            name=op.f("fk_jurisdiction_chain_jurisdiction_id_jurisdiction"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jurisdiction_chain")),
        sa.UniqueConstraint(
            "application_id",
            "jurisdiction_id",
            "role",
            name="uq_jurisdiction_chain_application_id_jurisdiction_id_role",
        ),
    )
    op.create_table(
        "objection",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=True),
        sa.Column("jurisdiction_id", sa.BigInteger(), nullable=False),
        sa.Column("observed_on", sa.Date(), nullable=True),
        sa.Column("organised", sa.Boolean(), nullable=True),
        sa.Column("group_cluster_id", sa.BigInteger(), nullable=True),
        sa.Column("group_name_raw", sa.Text(), nullable=True),
        sa.Column("retained_counsel", sa.Boolean(), nullable=True),
        sa.Column(
            "grounds", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False
        ),
        sa.Column("speakers", sa.Integer(), nullable=True),
        sa.Column("media_mentions", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "grounds <@ ARRAY['water', 'noise', 'traffic', 'electricity_cost', 'property_value', 'visual', 'environmental', 'process', 'tax', 'agricultural_land', 'public_safety', 'other']::text[]",
            name=op.f("ck_objection_grounds_vocabulary"),
        ),
        sa.CheckConstraint(
            "speakers IS NULL OR speakers >= 0",
            name=op.f("ck_objection_ck_objection_speakers_nonneg"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
            name=op.f("fk_objection_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_cluster_id"],
            ["entity_cluster.id"],
            name=op.f("fk_objection_group_cluster_id_entity_cluster"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdiction.id"],
            name=op.f("fk_objection_jurisdiction_id_jurisdiction"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_objection")),
    )
    op.create_index("ix_objection_application_id", "objection", ["application_id"], unique=False)
    op.create_index(
        "ix_objection_jurisdiction_id_observed_on",
        "objection",
        ["jurisdiction_id", "observed_on"],
        unique=False,
    )
    op.create_table(
        "precedent_link",
        sa.Column("a_id", sa.BigInteger(), nullable=False),
        sa.Column("b_id", sa.BigInteger(), nullable=False),
        sa.Column("similarity", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "basis",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Which dimensions matched, and by how much. Shown to the customer as the comparable set, so it has to be legible rather than a bare score.",
        ),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "a_id <> b_id", name=op.f("ck_precedent_link_ck_precedent_link_not_self")
        ),
        sa.CheckConstraint(
            "similarity >= 0 AND similarity <= 1",
            name=op.f("ck_precedent_link_ck_precedent_link_similarity_range"),
        ),
        sa.ForeignKeyConstraint(
            ["a_id"],
            ["application.id"],
            name=op.f("fk_precedent_link_a_id_application"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["b_id"],
            ["application.id"],
            name=op.f("fk_precedent_link_b_id_application"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("a_id", "b_id", name=op.f("pk_precedent_link")),
    )
    op.create_index("ix_precedent_link_b_id", "precedent_link", ["b_id"], unique=False)
    op.create_table(
        "prediction",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id",
            sa.Text(),
            nullable=False,
            comment="Opaque identifier used in the ledger and in URLs",
        ),
        sa.Column("application_id", sa.BigInteger(), nullable=True),
        sa.Column("jurisdiction_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "site",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Parcel ids, use class, relief sought, by_right",
        ),
        sa.Column("model_run_id", sa.BigInteger(), nullable=False),
        sa.Column("survival_run_id", sa.BigInteger(), nullable=True),
        sa.Column("rule_change_run_id", sa.BigInteger(), nullable=True),
        sa.Column("approval_probability", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("ci80_low", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("ci80_high", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("confidence", sa.Text(), nullable=True),
        sa.Column("abstained", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "abstention_reasons",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("months_p10", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("months_p50", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("months_p90", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("rule_change_probability", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column(
            "drivers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "precedents",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "mitigations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "alternatives",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "features_hash",
            sa.String(length=64),
            nullable=False,
            comment="Committed to the ledger so a prediction cannot be quietly re-based later",
        ),
        sa.Column("data_as_of", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "abstention_reasons <@ ARRAY['thin_local_record', 'dominated_by_pooling', 'interval_too_wide', 'stale_jurisdiction_data', 'unresolved_jurisdiction_chain']::text[]",
            name=op.f("ck_prediction_abstention_reasons_vocabulary"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence IN ('low', 'medium', 'high')",
            name=op.f("ck_prediction_confidence_vocabulary"),
        ),
        sa.CheckConstraint(
            "(abstained = true AND approval_probability IS NULL) OR (abstained = false AND approval_probability IS NOT NULL)",
            name=op.f("ck_prediction_ck_prediction_abstention_excludes_probability"),
        ),
        sa.CheckConstraint(
            "abstained = false OR cardinality(abstention_reasons) >= 1",
            name=op.f("ck_prediction_ck_prediction_abstention_has_reason"),
        ),
        sa.CheckConstraint(
            "approval_probability IS NULL OR (approval_probability >= 0 AND approval_probability <= 1)",
            name=op.f("ck_prediction_ck_prediction_probability_range"),
        ),
        sa.CheckConstraint(
            "approval_probability IS NULL OR ci80_low IS NOT NULL",
            name=op.f("ck_prediction_ck_prediction_point_estimate_needs_interval"),
        ),
        sa.CheckConstraint(
            "ci80_low IS NULL OR ci80_high IS NULL OR ci80_low <= ci80_high",
            name=op.f("ck_prediction_ck_prediction_interval_ordered"),
        ),
        sa.CheckConstraint(
            "months_p10 IS NULL OR months_p50 IS NULL OR months_p90 IS NULL OR (months_p10 <= months_p50 AND months_p50 <= months_p90)",
            name=op.f("ck_prediction_ck_prediction_months_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
            name=op.f("fk_prediction_application_id_application"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdiction.id"],
            name=op.f("fk_prediction_jurisdiction_id_jurisdiction"),
        ),
        sa.ForeignKeyConstraint(
            ["model_run_id"], ["model_run.id"], name=op.f("fk_prediction_model_run_id_model_run")
        ),
        sa.ForeignKeyConstraint(
            ["rule_change_run_id"],
            ["model_run.id"],
            name=op.f("fk_prediction_rule_change_run_id_model_run"),
        ),
        sa.ForeignKeyConstraint(
            ["survival_run_id"],
            ["model_run.id"],
            name=op.f("fk_prediction_survival_run_id_model_run"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prediction")),
        sa.UniqueConstraint("public_id", name="uq_prediction_public_id"),
    )
    op.create_index("ix_prediction_application_id", "prediction", ["application_id"], unique=False)
    op.create_index(
        "ix_prediction_jurisdiction_id_created_at",
        "prediction",
        ["jurisdiction_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "transcript_segment",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column(
            "speaker_label",
            sa.Text(),
            nullable=True,
            comment="Diarisation output, e.g. SPEAKER_03. Never presented to a customer on its own.",
        ),
        sa.Column(
            "maker_id",
            sa.BigInteger(),
            nullable=True,
            comment="Resolved only when the attribution is supported by the record",
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("agenda_item", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.CheckConstraint(
            "char_end >= char_start",
            name=op.f("ck_transcript_segment_ck_transcript_segment_offsets_ordered"),
        ),
        sa.CheckConstraint(
            "end_ms >= start_ms",
            name=op.f("ck_transcript_segment_ck_transcript_segment_time_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
            name=op.f("fk_transcript_segment_document_id_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["maker_id"],
            ["decision_maker.id"],
            name=op.f("fk_transcript_segment_maker_id_decision_maker"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_segment")),
        sa.UniqueConstraint(
            "document_id", "ordinal", name="uq_transcript_segment_document_id_ordinal"
        ),
    )
    op.create_index(
        "ix_transcript_segment_maker_id", "transcript_segment", ["maker_id"], unique=False
    )
    op.create_index(
        "ix_transcript_segment_text_fts",
        "transcript_segment",
        [sa.literal_column("to_tsvector('english', text)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "vote",
        sa.Column("application_id", sa.BigInteger(), nullable=False),
        sa.Column("maker_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Text(), nullable=False),
        sa.Column("voted_on", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "position IN ('for', 'against', 'abstain', 'absent', 'recused')",
            name=op.f("ck_vote_position_vocabulary"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
            name=op.f("fk_vote_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["maker_id"],
            ["decision_maker.id"],
            name=op.f("fk_vote_maker_id_decision_maker"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("application_id", "maker_id", name=op.f("pk_vote")),
    )
    op.create_index("ix_vote_maker_id", "vote", ["maker_id"], unique=False)
    op.create_table(
        "event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("jurisdiction_id", sa.BigInteger(), nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=True),
        sa.Column("instrument_id", sa.BigInteger(), nullable=True),
        sa.Column("body_id", sa.BigInteger(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column(
            "known_from",
            sa.Date(),
            nullable=False,
            comment="The date this became publicly knowable. Point in time features read this, not occurred_on, so a feature cannot see an event before the record existed.",
        ),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('application_filed', 'hearing_held', 'hearing_continued', 'staff_report_issued', 'decision_rendered', 'ordinance_adopted', 'ordinance_proposed', 'moratorium_enacted', 'moratorium_proposed', 'moratorium_expired', 'appeal_filed', 'litigation_filed', 'membership_changed')",
            name=op.f("ck_event_event_type_vocabulary"),
        ),
        sa.CheckConstraint(
            "known_from >= occurred_on", name=op.f("ck_event_ck_event_known_after_occurred")
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
            name=op.f("fk_event_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["body_id"],
            ["decision_body.id"],
            name=op.f("fk_event_body_id_decision_body"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
            name=op.f("fk_event_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdiction.id"],
            name=op.f("fk_event_jurisdiction_id_jurisdiction"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event")),
    )
    op.create_index("ix_event_application_id", "event", ["application_id"], unique=False)
    op.create_index(
        "ix_event_jurisdiction_id_event_type_known_from",
        "event",
        ["jurisdiction_id", "event_type", "known_from"],
        unique=False,
    )
    op.create_table(
        "ledger_entry",
        sa.Column("seq", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("prediction_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The exact record that was hashed. Stored verbatim so anyone can recompute.",
        ),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "prev_hash",
            sa.String(length=64),
            nullable=False,
            comment="64 zeros for the genesis entry",
        ),
        sa.Column(
            "entry_hash",
            sa.String(length=64),
            nullable=False,
            comment="sha256(prev_hash || payload_hash)",
        ),
        sa.Column(
            "anchor_reference", sa.Text(), nullable=True, comment="Independent timestamping receipt"
        ),
        sa.Column("resolved_outcome", sa.Text(), nullable=True),
        sa.Column("resolved_on", sa.Date(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "grading",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Brier contribution, interval hit, note",
        ),
        sa.Column(
            "miss_note",
            sa.Text(),
            nullable=True,
            comment="Section 8.5. Written explanation of what the model missed, published as is.",
        ),
        sa.CheckConstraint(
            "entry_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_ledger_entry_ck_ledger_entry_entry_hash_format"),
        ),
        sa.CheckConstraint(
            "payload_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_ledger_entry_ck_ledger_entry_payload_hash_format"),
        ),
        sa.CheckConstraint(
            "prev_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_ledger_entry_ck_ledger_entry_prev_hash_format"),
        ),
        sa.CheckConstraint(
            "resolved_outcome IS NULL OR resolved_outcome IN ('approved', 'approved_with_conditions', 'denied', 'withdrawn', 'continued', 'tabled', 'pending', 'unknown')",
            name=op.f("ck_ledger_entry_resolved_outcome_vocabulary"),
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["prediction.id"],
            name=op.f("fk_ledger_entry_prediction_id_prediction"),
        ),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_ledger_entry")),
        sa.UniqueConstraint("entry_hash", name="uq_ledger_entry_entry_hash"),
        sa.UniqueConstraint("prediction_id", name="uq_ledger_entry_prediction_id"),
    )
    op.create_index("ix_ledger_entry_published_at", "ledger_entry", ["published_at"], unique=False)
    op.create_index(
        "ix_ledger_entry_unresolved",
        "ledger_entry",
        ["published_at"],
        unique=False,
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.create_table(
        "watch",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "subscriber", sa.Text(), nullable=False, comment="API key label until billing exists"
        ),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("jurisdiction_id", sa.BigInteger(), nullable=False),
        sa.Column("site", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_prediction_id", sa.BigInteger(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["jurisdiction_id"],
            ["jurisdiction.id"],
            name=op.f("fk_watch_jurisdiction_id_jurisdiction"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["last_prediction_id"],
            ["prediction.id"],
            name=op.f("fk_watch_last_prediction_id_prediction"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch")),
        sa.UniqueConstraint("subscriber", "label", name="uq_watch_subscriber_label"),
    )
    op.create_index(
        "ix_watch_jurisdiction_id_active", "watch", ["jurisdiction_id", "active"], unique=False
    )
    op.create_table(
        "alert",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("watch_id", sa.BigInteger(), nullable=False),
        sa.Column("change_event_id", sa.BigInteger(), nullable=False),
        sa.Column("materiality", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("score_before", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("score_after", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suppressed_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["change_event_id"],
            ["change_event.id"],
            name=op.f("fk_alert_change_event_id_change_event"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["watch_id"], ["watch.id"], name=op.f("fk_alert_watch_id_watch"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert")),
        sa.UniqueConstraint(
            "watch_id", "change_event_id", name="uq_alert_watch_id_change_event_id"
        ),
    )
    op.create_index(
        "ix_alert_undelivered",
        "alert",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("delivered_at IS NULL AND suppressed_reason IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_alert_undelivered",
        table_name="alert",
        postgresql_where=sa.text("delivered_at IS NULL AND suppressed_reason IS NULL"),
    )
    op.drop_table("alert")
    op.drop_index("ix_watch_jurisdiction_id_active", table_name="watch")
    op.drop_table("watch")
    op.drop_index(
        "ix_ledger_entry_unresolved",
        table_name="ledger_entry",
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.drop_index("ix_ledger_entry_published_at", table_name="ledger_entry")
    op.drop_table("ledger_entry")
    op.drop_index("ix_event_jurisdiction_id_event_type_known_from", table_name="event")
    op.drop_index("ix_event_application_id", table_name="event")
    op.drop_table("event")
    op.drop_index("ix_vote_maker_id", table_name="vote")
    op.drop_table("vote")
    op.drop_index(
        "ix_transcript_segment_text_fts", table_name="transcript_segment", postgresql_using="gin"
    )
    op.drop_index("ix_transcript_segment_maker_id", table_name="transcript_segment")
    op.drop_table("transcript_segment")
    op.drop_index("ix_prediction_jurisdiction_id_created_at", table_name="prediction")
    op.drop_index("ix_prediction_application_id", table_name="prediction")
    op.drop_table("prediction")
    op.drop_index("ix_precedent_link_b_id", table_name="precedent_link")
    op.drop_table("precedent_link")
    op.drop_index("ix_objection_jurisdiction_id_observed_on", table_name="objection")
    op.drop_index("ix_objection_application_id", table_name="objection")
    op.drop_table("objection")
    op.drop_table("jurisdiction_chain")
    op.drop_index(
        "ix_instrument_live_moratorium",
        table_name="instrument",
        postgresql_where=sa.text("kind = 'moratorium'"),
    )
    op.drop_index("ix_instrument_jurisdiction_id_kind_effective_on", table_name="instrument")
    op.drop_table("instrument")
    op.drop_index("ix_fetch_attempt_source_id_attempted_at", table_name="fetch_attempt")
    op.drop_table("fetch_attempt")
    op.drop_index("ix_feature_snapshot_as_of", table_name="feature_snapshot")
    op.drop_table("feature_snapshot")
    op.drop_index(
        "ix_fact_evidence_unverified",
        table_name="fact_evidence",
        postgresql_where=sa.text("verified = false"),
    )
    op.drop_index("ix_fact_evidence_subject_table_subject_id", table_name="fact_evidence")
    op.drop_index("ix_fact_evidence_document_id", table_name="fact_evidence")
    op.drop_table("fact_evidence")
    op.drop_index("ix_extraction_run_status_created_at", table_name="extraction_run")
    op.drop_index("ix_extraction_run_document_id", table_name="extraction_run")
    op.drop_table("extraction_run")
    op.drop_index(
        "ix_entity_alias_normalised_trgm",
        table_name="entity_alias",
        postgresql_using="gin",
        postgresql_ops={"normalised": "gin_trgm_ops"},
    )
    op.drop_table("entity_alias")
    op.drop_table("document_page")
    op.drop_index("ix_document_chunk_text_fts", table_name="document_chunk", postgresql_using="gin")
    op.drop_index(
        "ix_document_chunk_embedding_hnsw",
        table_name="document_chunk",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    op.drop_table("document_chunk")
    op.drop_index("ix_change_event_jurisdiction_id_detected_on", table_name="change_event")
    op.drop_table("change_event")
    op.drop_index("ix_election_election_date", table_name="election")
    op.drop_table("election")
    op.drop_index("ix_document_source_url", table_name="document")
    op.drop_index("ix_document_jurisdiction_id_kind_published_on", table_name="document")
    op.drop_index("ix_document_fetched_at", table_name="document")
    op.drop_index(
        "ix_document_embedding_hnsw",
        table_name="document",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    op.drop_table("document")
    op.drop_index(
        "ix_decision_maker_display_name_trgm",
        table_name="decision_maker",
        postgresql_using="gin",
        postgresql_ops={"display_name": "gin_trgm_ops"},
    )
    op.drop_index("ix_decision_maker_body_id", table_name="decision_maker")
    op.drop_table("decision_maker")
    op.drop_index(
        "ix_application_pending",
        table_name="application",
        postgresql_where=sa.text("censored = true"),
    )
    op.drop_index("ix_application_outcome_decided_on", table_name="application")
    op.drop_index("ix_application_jurisdiction_id_use_class_decided_on", table_name="application")
    op.drop_index("ix_application_filed_on", table_name="application")
    op.drop_index("ix_application_applicant_cluster_id", table_name="application")
    op.drop_table("application")
    op.drop_index("ix_source_enabled_last_success_at", table_name="source")
    op.drop_table("source")
    op.drop_index("ix_parcel_owner_cluster_id", table_name="parcel")
    op.drop_index("ix_parcel_jurisdiction_id_external_id", table_name="parcel")
    op.drop_index("ix_parcel_geom", table_name="parcel", postgresql_using="gist")
    op.drop_table("parcel")
    op.drop_table("decision_body")
    op.drop_index(
        "ix_dead_letter_open",
        table_name="dead_letter",
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.drop_table("dead_letter")
    op.drop_index(
        "ix_model_run_serving",
        table_name="model_run",
        postgresql_where=sa.text("retired_at IS NULL"),
    )
    op.drop_table("model_run")
    op.drop_table("merge_audit")
    op.drop_index("ix_jurisdiction_region_kind", table_name="jurisdiction")
    op.drop_index(
        "ix_jurisdiction_name_trgm",
        table_name="jurisdiction",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index("ix_jurisdiction_boundary", table_name="jurisdiction", postgresql_using="gist")
    op.drop_table("jurisdiction")
    op.drop_index(
        "ix_entity_cluster_canonical_name_trgm",
        table_name="entity_cluster",
        postgresql_using="gin",
        postgresql_ops={"canonical_name": "gin_trgm_ops"},
    )
    op.drop_table("entity_cluster")
    # ### end Alembic commands ###
