"""Synthetic corpora, for testing model mathematics against a known ground truth.

Read this before using anything in here.

**Nothing generated by this module is ever used for a published claim.** It is not in the
specification and it is not part of the pipeline. It exists for one reason: to prove that the
calibration mathematics, the pooling behaviour and the survival estimator are correct, which cannot be
established on real data because on real data the truth is unknown.

``auspice eval kill-test`` reads from the database and has no code path that reaches this module. The
separation is enforced by ``tests/unit/test_synthetic_is_isolated.py``.

## The generative model

Section 6.8, written out:

    logit(p_i) = a_j + X_i . b
    a_j  ~ Normal(mu_c, sigma)
    mu_c ~ Normal(mu_0, tau)

The important design decision is how the jurisdiction effect ``a_j`` reaches an observable feature,
because getting it wrong makes the whole exercise misleading.

In the first version of this generator the history features were drawn independently of ``a_j``. That
made ``approval_rate_juris_use`` pure noise, while the base rate model got jurisdiction identity
directly, so the boosted model lost to the base rate by nine percent and the finding said nothing about
either model. It was an artefact of the generator.

In the real system a jurisdiction's approval history *is* the channel through which its disposition
reaches the model. So here the history features are **measurements of** ``a_j``, with sampling noise
scaled to the jurisdiction's depth, exactly as a real observed rate would be. Their causal coefficient
is zero, because they do not cause the outcome; they carry information about the intercept that does.

That structure means both models see the same information through different routes, which is the only
setup in which comparing them means anything.

Jurisdiction depth is drawn skewed on purpose, so most jurisdictions have a handful of decisions and a
few have dozens. That is the shape section 4.5 describes and the regime where pooling earns its place.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, timedelta
from typing import Any

import numpy as np
import polars as pl

SYNTHETIC_MARKER = "synthetic"

# Features whose value is caused by the jurisdiction intercept rather than causing the outcome. They
# are measurements of a_j, and their coefficient in the generative model is zero.
MEASUREMENT_FEATURES: tuple[str, ...] = (
    "approval_rate_juris_use",
    "denial_streak",
)

# Features that genuinely move the outcome.
CAUSAL_FEATURES: tuple[str, ...] = (
    "relief_count",
    "days_since_rule_change",
    "moratorium_active",
    "months_to_next_election",
    "objection_density_24m",
    "organised_group_present",
    "capacity_mw",
    "applicant_track_record",
)

FEATURE_COLUMNS: tuple[str, ...] = (*MEASUREMENT_FEATURES, *CAUSAL_FEATURES)

TRUE_COEFFICIENTS: dict[str, float] = {
    # Zero, and not because they do not matter. They carry a_j, which matters more than anything
    # else in the model. See the module docstring.
    "approval_rate_juris_use": 0.0,
    "denial_streak": 0.0,
    # Causal effects, on the logit scale, against covariates drawn on the scales below.
    "relief_count": -0.45,
    "days_since_rule_change": 0.35,
    "moratorium_active": -1.70,
    "months_to_next_election": 0.30,
    "objection_density_24m": -0.55,
    "organised_group_present": -0.80,
    "capacity_mw": -0.22,
    "applicant_track_record": 0.60,
}


@dataclass(slots=True)
class SyntheticCorpus:
    frame: pl.DataFrame
    feature_columns: list[str]
    true_coefficients: dict[str, float]
    true_probabilities: np.ndarray
    jurisdiction_intercepts: dict[str, float]
    cluster_means: dict[str, float]
    mu_0: float
    tau: float
    sigma: float
    notes: list[str] = field(default_factory=list)

    @property
    def depth(self) -> dict[str, int]:
        counts = self.frame.group_by("jurisdiction").len().iter_rows(named=True)
        return {row["jurisdiction"]: int(row["len"]) for row in counts}

    @property
    def causal_coefficients(self) -> dict[str, float]:
        return {k: v for k, v in self.true_coefficients.items() if v != 0.0}


def generate(
    *,
    n_jurisdictions: int = 24,
    n_clusters: int = 4,
    target_base_rate: float = 0.52,
    tau: float = 0.60,
    sigma: float = 0.50,
    missing_rate: float = 0.12,
    censoring_rate: float = 0.12,
    withdrawal_share: float = 0.10,
    depth_shape: float = 2.6,
    depth_scale: float = 14.0,
    start: date = date(2019, 1, 1),
    end: date = date(2026, 6, 30),
    seed: int = 20260827,
) -> SyntheticCorpus:
    """Draw a corpus from the section 6.8 generative model.

    ``target_base_rate`` is honoured by solving for ``mu_0`` rather than by setting it by hand. The
    covariates have non-zero means, so a hand set intercept produces whatever base rate falls out, and
    a corpus with a 23 percent approval rate is not the regime this product operates in.
    """
    rng = np.random.default_rng(seed)

    causal_vector = np.asarray(
        [TRUE_COEFFICIENTS[name] for name in CAUSAL_FEATURES], dtype=np.float64
    )

    # Solve for mu_0 by bisection on a monotone function.
    probe = np.asarray(
        [
            [row[name] for name in CAUSAL_FEATURES]
            for row in (_draw_causal(rng) for _ in range(6000))
        ],
        dtype=np.float64,
    )
    probe_linear = probe @ causal_vector
    low, high = -14.0, 14.0
    for _ in range(90):
        mid = (low + high) / 2.0
        if float(np.mean(1.0 / (1.0 + np.exp(-(mid + probe_linear))))) < target_base_rate:
            low = mid
        else:
            high = mid
    mu_0 = (low + high) / 2.0

    cluster_names = [f"cluster-{i}" for i in range(n_clusters)]
    cluster_means = {name: float(mu_0 + tau * rng.standard_normal()) for name in cluster_names}

    frameworks = ["dillons_rule", "home_rule", "mixed"]
    jurisdictions: list[dict[str, Any]] = []
    intercepts: dict[str, float] = {}

    for index in range(n_jurisdictions):
        slug = f"synthetic-{index:02d}"
        cluster = cluster_names[index % n_clusters]
        intercepts[slug] = float(cluster_means[cluster] + sigma * rng.standard_normal())
        depth = int(np.clip(rng.gamma(shape=depth_shape, scale=depth_scale), 3, 90))
        jurisdictions.append(
            {
                "slug": slug,
                "cluster": cluster,
                "depth": depth,
                "legal_framework": frameworks[index % len(frameworks)],
                "discretion_index": float(np.clip(rng.beta(4, 2), 0.05, 0.98)),
                "region": f"S{index % 6}",
            }
        )

    rows: list[dict[str, object]] = []
    true_probabilities: list[float] = []
    span_days = (end - start).days

    for jurisdiction in jurisdictions:
        slug = str(jurisdiction["slug"])
        depth = int(jurisdiction["depth"])
        alpha = intercepts[slug]

        # The jurisdiction's true long run approval rate, and what an observer measuring it from
        # ``depth`` decisions would see. Standard error of a proportion, so a jurisdiction with five
        # decisions has a noisy history feature and one with fifty has a sharp one. That is exactly
        # the relationship the pooling weight exists to handle.
        true_rate = float(1.0 / (1.0 + np.exp(-alpha)))
        measurement_sd = float(np.sqrt(max(true_rate * (1.0 - true_rate), 0.01) / max(depth, 1)))

        for _ in range(depth):
            causal = _draw_causal(rng)
            x = np.asarray([causal[name] for name in CAUSAL_FEATURES], dtype=np.float64)
            logit = alpha + float(x @ causal_vector)
            p = 1.0 / (1.0 + np.exp(-logit))
            approved = bool(rng.random() < p)
            true_probabilities.append(float(p))

            observed_rate = float(np.clip(true_rate + rng.normal(0.0, measurement_sd), 0.0, 1.0))
            # A denial streak is a consequence of a low approval rate, not a cause of anything.
            observed_streak = float(rng.poisson(max(0.05, 2.2 * (1.0 - true_rate))))

            filed = start + timedelta(days=int(rng.integers(0, max(span_days - 200, 1))))
            # Duration depends on the same covariates, so the survival model has real signal, and
            # more contested applications take longer.
            scale = float(np.exp(2.35 - 0.30 * logit + 0.25 * causal["relief_count"]))
            months = float(np.clip(rng.weibull(1.7) * scale, 0.5, 96.0))
            decided = filed + timedelta(days=int(months * 30.44))

            # Censoring is administrative: the observation window ended before the decision
            # landed. That is how the real corpus is censored, and it is the only kind that keeps
            # the censoring time and the filing date consistent. A random dropout would leave a row
            # marked pending with an elapsed time far longer than its true duration, which makes the
            # survival estimate look badly biased when in fact the generator was wrong.
            stalled = rng.random() < censoring_rate
            decided_effective = end + timedelta(days=1) if stalled else decided
            censored = decided_effective > end
            if censored:
                outcome, risk, decided_on, months_to_decision = "pending", "censored", None, None
            elif not approved and rng.random() < withdrawal_share:
                outcome, risk, decided_on, months_to_decision = (
                    "withdrawn",
                    "withdrawal",
                    decided,
                    months,
                )
            elif approved:
                outcome, risk, decided_on, months_to_decision = (
                    "approved",
                    "approval",
                    decided,
                    months,
                )
            else:
                outcome, risk, decided_on, months_to_decision = "denied", "denial", decided, months

            row: dict[str, Any] = {
                "application_id": len(rows) + 1,
                "jurisdiction": slug,
                "region": str(jurisdiction["region"]),
                "legal_framework": str(jurisdiction["legal_framework"]),
                "use_class": "data_center_hyperscale",
                "outcome": outcome,
                "approved": 1 if approved else 0,
                "censored": censored,
                "risk": risk,
                "filed_on": filed,
                "decided_on": decided_on,
                "as_of": filed,
                "months_to_decision": months_to_decision,
                "n_missing": 0,
                "discretion_index": float(jurisdiction["discretion_index"]),
                "home_rule": 1.0 if jurisdiction["legal_framework"] == "home_rule" else 0.0,
                "n_comparable_decisions": float(depth),
                "approval_rate_juris_use": observed_rate,
                "denial_streak": observed_streak,
            }
            row.update({name: float(causal[name]) for name in CAUSAL_FEATURES})
            rows.append(row)

    frame = pl.DataFrame(rows)

    # Puncture the frame the way the real corpus arrives. Applied after the outcome is drawn, so the
    # truth is unaffected and the model has to cope with an incomplete view of a world that really did
    # generate the data.
    if missing_rate > 0:
        for name in FEATURE_COLUMNS:
            mask = rng.random(frame.height) < missing_rate
            frame = frame.with_columns(
                pl.when(pl.Series(mask)).then(None).otherwise(pl.col(name)).alias(name)
            )
        frame = frame.with_columns(
            pl.sum_horizontal(
                [pl.col(name).is_null().cast(pl.Int64) for name in FEATURE_COLUMNS]
            ).alias("n_missing")
        )

    return SyntheticCorpus(
        frame=frame,
        feature_columns=list(FEATURE_COLUMNS),
        true_coefficients=dict(TRUE_COEFFICIENTS),
        true_probabilities=np.asarray(true_probabilities, dtype=np.float64),
        jurisdiction_intercepts=intercepts,
        cluster_means=cluster_means,
        mu_0=mu_0,
        tau=tau,
        sigma=sigma,
        notes=[
            "synthetic corpus, generated from the section 6.8 model",
            "for testing model mathematics only, never for a published claim",
        ],
    )


def _draw_causal(rng: np.random.Generator) -> dict[str, float]:
    """One row of causal covariates, on roughly the scales the real features take."""
    return {
        "relief_count": float(rng.integers(1, 4)),
        # Centred so the coefficient is interpretable: negative means a recent rule change.
        "days_since_rule_change": float(np.clip(rng.gamma(2.0, 500.0) / 1000.0 - 1.0, -1.0, 4.0)),
        "moratorium_active": float(rng.random() < 0.10),
        "months_to_next_election": float(np.clip(rng.uniform(0, 48) / 12.0 - 2.0, -2.0, 2.0)),
        "objection_density_24m": float(np.clip(rng.gamma(1.5, 0.6), 0.0, 6.0)),
        "organised_group_present": float(rng.random() < 0.35),
        "capacity_mw": float(np.clip(rng.lognormal(4.5, 0.8) / 100.0, 0.0, 12.0)),
        "applicant_track_record": float(np.clip(rng.beta(6, 3), 0.0, 1.0)),
    }
